config/routes.rb
HitcentsParkPlaza::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount HitcentsAuth::Engine, :at => '/hitcents', :as => 'hitcents'

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'pages#home'

  get "eat/:restaurant/menus" => 'menus#index'
  get "eat/:restaurant/menu/:id" => 'menus#show'

  get "eat/" => 'restaurants#index', :as => 'eat'
  get "eat/:restaurant" => 'restaurants#show'

  get "eat/:restaurant/careers" => 'job_openings#show'
  get "work/careers" => 'job_openings#index'
  get "job_openings/:id/job_applications" => 'job_applications#new'

  get "eat/:restaurant/photos" => 'gallery_photos#show'
  get "/photos" => 'gallery_photos#index'

  get "work" => 'pages#work', :as => 'work'

  get "play" => 'special_events#index', :as => 'play'
  get "banquet" => 'banquet_menu_items#index', :as => 'banquet'

  get "about" => 'pages#about', :as => 'about'
  get "contact" => 'pages#contact', :as => 'contact'
  get "rewards" => 'pages#rewards', :as => 'rewards'

  resource :email_submissions, only: [:create]

  resources :restaurants do
    resources :job_openings
    resources :menus
    resources :gallery_photos
  end

  resources :job_openings do
    resource :job_applications, only: [:new, :create]
  end

  resources :gallery_photos
  resources :special_events
  resources :gift_cards

  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/banquet_menu_item.rb
class BanquetMenuItem < ActiveRecord::Base
  has_attached_file :image
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :menu
  has_many :menu_items
end

app/models/email_submission.rb
class EmailSubmission < ActiveRecord::Base
  validates :email, presence: true
end

app/models/gallery_photo.rb
class GalleryPhoto < ActiveRecord::Base
  belongs_to :restaurant

  has_attached_file :photo,
    :styles => { :photo => "386x224", :thumb => "150x100>" }
end

app/models/gift_card.rb
class GiftCard < ActiveRecord::Base
end

app/models/job_application.rb
class JobApplication < ActiveRecord::Base
  belongs_to :job_opening

  validates_presence_of :email, :name, :last_name, :job_opening_id
end

app/models/job_opening.rb
class JobOpening < ActiveRecord::Base

  belongs_to :restaurant
  has_many :job_applications
  before_save do
    self.post_date = Date.today
  end

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :restaurant
  has_many :categories

  accepts_nested_attributes_for :categories
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :category

  has_attached_file :image
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_attached_file :photo,
    :styles => { :photo => "386x224", :thumb => "150x100>" },
    :default_url => "/images/:style/missing.png"

  has_many :menus
  has_many :special_events
  has_many :job_openings
  has_many :gallery_photos
end

app/models/special_event.rb
class SpecialEvent < ActiveRecord::Base
  belongs_to :restaurant

  has_attached_file :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :determine_restaurant, :email_submission

  def determine_restaurant
    if params[:restaurant]
      @@restaurant = Restaurant.find_by_name(params[:restaurant])
    end
  end

  def email_submission
    @email_submission = EmailSubmission.new
  end
end

app/controllers/gift_cards_controller.rb
class GiftCardsController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = @@restaurant.menus
  end

  def show
    @menu = Menu.find_by_id(params[:id])
    @menu_items = @menu.menu_items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

    # render :coming_soon
  end

  def work
  end

  def play
  end

  def about
  end

  def contact
  end

  def rewards
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_openings_helper.rb
module JobOpeningsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "HitcentsParkPlaza"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    = javascript_include_tag 'ckeditor/ckeditor.js'


  %body{:class => "#{controller_name} #{action_name}"}
    .container-fluid
      .row-fluid
        = render :partial => 'shared/nav'


        .span10

          = render :partial => 'shared/toolbar'
          = bootstrap_flash
          = yield
          = render :partial => 'shared/footer'
    :javascript
      $(document).ready(function() {
        if ($('textarea').length > 0) {
          var data = $('textarea');
          $.each(data, function(i) {
            CKEDITOR.replace(data[i].id);
          });
        }
      });

      %footer
        %p &copy; Company 2014

app/views/pages/about.html.haml
About page

app/views/pages/coming_soon.html.haml
.container
  .row-fluid
    %h1.logo Hitcents Park Plaza

  .row-fluid.work-eat-play
    %h2 Work. Eat. Play.
    %p.lead
      The most UNIQUE business, dining, &amp; entertainment possibilities around.
      %br
      Combined into one building in downtown Bowling Green.

  .row-fluid
    %p.sign-up-for-latest Sign up for the latest news about grand openings &amp; more

  .row-fluid.sign-up
    .email-submission-form-msg
    = form_for(@email_submission, remote: true) do |f|
      .form-group
        = f.email_field :email, { placeholder: "Enter your email address", class: "col-xs-10" }
        = f.submit "JOIN >"

app/views/pages/contact.html.haml
Contact page

app/views/pages/home.html.haml
.row-fluid.buckets
  %div.span4.work.bucket
    .block#1
    = link_to "WORK.", work_path

  %div.span4.eat.bucket
    .block#2
    = link_to "EAT.", eat_path

  %div.span4.play.bucket
    .block#3
    = link_to "PLAY.", play_path

app/views/pages/play.html.haml
- unless @special_events.nil?
  - @special_events.each do |event|
    .span2
      = link_to event.image.url, special_event_path(event)

app/views/pages/rewards.html.haml
Rewards page

app/views/pages/work.html.haml
Yo work goes here!

app/views/shared/_footer.html.haml
.navbar.footer
  %ul.nav
    %li
      = link_to 'ABOUT', about_path
    %li
      = link_to '|'
    %li
      = link_to 'REWARDS', rewards_path
    %li
      = link_to '|'
    %li
      = link_to 'GIFTCARD BALANCE'
    %li
      = link_to '|'
    %li
      = link_to 'CONTACT', contact_path
    %li
      = link_to '|'
    %li
      = link_to 'CITY CENTER'
    %li
      = link_to '|'
    %li
      = link_to 'COPYRIGHT   2014 HITCENTS PARK PLAZA'

app/views/shared/_nav.html.haml
.span2
  .navbar.navbar-fixed
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand
          = link_to image_tag("hpp-logo-home.png"), '/'
        %br
        %br
        The most UNIQUE business,
        %br
        dining & entertainment
        %br
        possibilities around.
        %br
        %br
        Combined into one building in downtown Bowling Green.
        .container.nav-collapse
          %ul.sidebar-nav
            %hr
            %li= link_to "WORK.", work_path
            %hr
            %li= link_to "EAT.", eat_path
            %hr
            %li= link_to "PLAY.", play_path
            %hr
            %li= link_to "GIFT CARDS.", gift_cards_path
            %hr
            %li= link_to "BANQUET.", banquet_path
            %hr
            %li= link_to "ORDER TO GO", "/path3"
            %hr
    .sign-up
      .email-submission-form-msg
      = form_for(@email_submission, remote: true) do |f|
        .form-group
          Get news & event updates.
          = f.email_field :email, { placeholder: "YOUR EMAIL ADDRESS", class: "col-xs-10" }
          = image_submit_tag('submit-arrow.png')
        %hr
        .social
          = image_tag('twitter.png')
          = image_tag('facebook.png')
          = image_tag('video.png')

app/views/shared/_toolbar.html.haml
.navbar.navbar-top-fixed
  .navbar-inner
    %a.brand
      January 2014
      .arrows
        = link_to image_tag('left-arrow.png')
        = link_to image_tag('right-arrow.png')
    %ul.top-nav
      %li= link_to image_tag('gridIcon.png'), '/'
      %li= link_to image_tag('listIcon.png'), '/'